server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: CUSTOMER-SERVICE
          uri: http://localhost:8087/
          predicates:
            - Path=/customer/**
        - id: account-service
          uri: http://localhost:8088/
          predicates:
            - Path=/account/**
        - id: PRODUCT-SERVICE
          uri: http://localhost:8086/
          predicates:
            - Path=/product/**
        - id: MOVEMENT-SERVICE
          uri: http://localhost:8089/
          predicates:
            - Path=/movement/**
